// src/client.tsx
import {
  isRecord,
  type AuthenticatedUser,
  type AuthSession,
} from "./auth-model.ts";
import { requestJson } from "./browser-http.ts";
import { providerNotice } from "./client-notices.ts";
import { createElement, mount, type JsxNode } from "./jsx.ts";
import {
  OPENAI_PANEL,
  OPENROUTER_PANEL,
  renderProviderPanel,
  type ProviderViewState,
} from "./provider-client.tsx";
import { ProviderController } from "./provider-controller.ts";
import {
  AUTH_GOOGLE_PATH,
  AUTH_LOGOUT_PATH,
  AUTH_SESSION_PATH,
  HOME_PATH,
} from "./routes.ts";
import { renderRunnerPanel, type RunnerViewState } from "./runner-client.tsx";
import { RunnerController } from "./runner-controller.ts";
import {
  renderSessionPanel,
  type SessionViewState,
} from "./session-client.tsx";
import { SessionController } from "./session-controller.ts";

function readAuthenticatedUser(value: unknown): AuthenticatedUser | null {
  if (value === null) {
    return null;
  }

  if (!isRecord(value)) {
    throw new Error("The session contained an invalid user");
  }

  const email = value["email"];
  const id = value["id"];
  const name = value["name"];
  const picture = value["picture"];

  if (
    typeof email !== "string" ||
    typeof id !== "string" ||
    typeof name !== "string" ||
    (picture !== undefined && typeof picture !== "string")
  ) {
    throw new Error("The session contained an invalid Google profile");
  }

  return picture === undefined
    ? { email, id, name }
    : { email, id, name, picture };
}

function readAuthSession(value: unknown): AuthSession {
  if (!isRecord(value)) {
    throw new Error("The server returned an invalid session");
  }

  const googleLoginAvailable = value["googleLoginAvailable"];

  if (typeof googleLoginAvailable !== "boolean") {
    throw new Error("The server returned an invalid login status");
  }

  return {
    googleLoginAvailable,
    user: readAuthenticatedUser(value["user"]),
  };
}

function readNotices(): readonly string[] {
  const url = new URL(window.location.href);
  const authResult = url.searchParams.get("auth");
  const openAiResult = url.searchParams.get("openai");
  const openRouterResult = url.searchParams.get("openrouter");
  const notices = [
    providerNotice("google", authResult),
    providerNotice("openai", openAiResult),
    providerNotice("openrouter", openRouterResult),
  ].filter((notice) => notice !== undefined);

  if (
    authResult !== null ||
    openAiResult !== null ||
    openRouterResult !== null
  ) {
    url.searchParams.delete("auth");
    url.searchParams.delete("openai");
    url.searchParams.delete("openrouter");
    window.history.replaceState(
      null,
      "",
      `${url.pathname}${url.search}${url.hash}`,
    );
  }

  return notices;
}

function renderAvatar(user: AuthenticatedUser): JsxNode {
  if (user.picture !== undefined) {
    return (
      <img
        alt=""
        className="size-12 rounded-2xl bg-slate-800 object-cover ring-1 ring-white/10"
        referrerpolicy="no-referrer"
        src={user.picture}
      />
    );
  }

  return (
    <span
      aria-hidden="true"
      className="grid size-12 place-items-center rounded-2xl bg-gradient-to-br from-emerald-300 to-cyan-400 text-lg font-bold text-slate-950"
    >
      {user.name.charAt(0).toUpperCase()}
    </span>
  );
}

function renderHeader(user: AuthenticatedUser | null | undefined): JsxNode {
  return (
    <header className="flex items-center justify-between gap-4 border-b border-white/10 pb-6">
      <a
        className="inline-flex items-center gap-3 rounded-full font-semibold text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-300"
        href={HOME_PATH}
      >
        <span
          aria-hidden="true"
          className="grid size-10 place-items-center rounded-xl bg-gradient-to-br from-emerald-300 to-cyan-400 text-xl shadow-lg shadow-emerald-950/50"
        >
          🍄
        </span>
        Q Mush
      </a>
      <span className="inline-flex min-w-0 items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/10 px-3 py-1 text-sm text-emerald-200">
        <span
          aria-hidden="true"
          className="size-2 shrink-0 rounded-full bg-emerald-300"
        ></span>
        {user === undefined
          ? "Checking session"
          : user === null
            ? "Local runtime"
            : `Signed in as ${user.name}`}
      </span>
    </header>
  );
}

function renderLoadingCard(): JsxNode {
  return (
    <div
      className="mt-12 rounded-3xl border border-white/10 bg-white/[0.06] p-8 shadow-2xl shadow-emerald-950/30 backdrop-blur-xl"
      role="status"
    >
      <div className="flex items-center gap-4">
        <span
          aria-hidden="true"
          className="size-3 animate-pulse rounded-full bg-emerald-300 shadow-[0_0_18px_rgba(110,231,183,0.8)]"
        ></span>
        <p className="font-medium text-slate-200">Checking your session…</p>
      </div>
    </div>
  );
}

function renderSessionError(): JsxNode {
  return (
    <div
      className="mt-12 rounded-3xl border border-rose-300/20 bg-rose-300/10 p-8"
      role="alert"
    >
      <p className="text-sm font-medium text-rose-200">Connection problem</p>
      <h2 className="mt-3 text-2xl font-semibold text-white">
        We could not check your session
      </h2>
      <p className="mt-3 max-w-xl leading-7 text-slate-300">
        Make sure the local server is running, then try again.
      </p>
      <button
        className="mt-7 rounded-full border border-white/15 px-5 py-2.5 font-semibold text-white transition hover:border-emerald-300/40 hover:text-emerald-200 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-300"
        data-action="retry-session"
        type="button"
      >
        Retry
      </button>
    </div>
  );
}

function renderSignIn(googleLoginAvailable: boolean): JsxNode {
  return (
    <div className="mt-12 grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem]">
      <section
        aria-labelledby="sign-in-title"
        className="rounded-3xl border border-white/10 bg-white/[0.06] p-7 shadow-2xl shadow-emerald-950/30 backdrop-blur-xl sm:p-10"
      >
        <p className="text-sm font-medium text-emerald-300">Secure access</p>
        <h2
          className="mt-3 text-3xl font-semibold tracking-tight text-white"
          id="sign-in-title"
        >
          Sign in to your control center
        </h2>
        <p className="mt-4 max-w-xl leading-7 text-slate-400">
          Use your Google Account to identify yourself. Your Q Mush session
          remains on this machine.
        </p>
        {googleLoginAvailable ? (
          <a
            className="mt-8 inline-flex w-full items-center justify-center gap-3 rounded-2xl bg-white px-5 py-3 font-semibold text-slate-900 shadow-lg shadow-black/20 transition hover:bg-slate-100 active:translate-y-px focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-cyan-300 sm:w-auto"
            href={AUTH_GOOGLE_PATH}
          >
            <span
              aria-hidden="true"
              className="grid size-6 place-items-center rounded-full text-base font-bold text-[#4285f4] ring-1 ring-slate-200"
            >
              G
            </span>
            Continue with Google
          </a>
        ) : (
          <div className="mt-8 rounded-2xl border border-amber-300/20 bg-amber-300/10 p-5 text-amber-100">
            <p className="font-medium">Google login needs configuration</p>
            <p className="mt-2 text-sm leading-6 text-amber-100/70">
              Set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET on the local server,
              then restart it.
            </p>
          </div>
        )}
      </section>

      <aside
        aria-label="Login details"
        className="rounded-3xl border border-white/10 bg-slate-900/80 p-7 sm:p-8"
      >
        <span
          aria-hidden="true"
          className="grid size-12 place-items-center rounded-2xl border border-cyan-300/20 bg-cyan-300/10 text-xl"
        >
          🔐
        </span>
        <h2 className="mt-6 text-lg font-semibold text-white">
          A small identity boundary
        </h2>
        <ul className="mt-5 space-y-4 text-sm leading-6 text-slate-400">
          <li>Google verifies your account.</li>
          <li>Only your basic profile and email are requested.</li>
          <li>No Google access token is kept after sign-in.</li>
        </ul>
      </aside>
    </div>
  );
}

function renderWorkspace(
  logoutPending: boolean,
  openAiState: ProviderViewState,
  openRouterState: ProviderViewState,
  runnerState: RunnerViewState,
  sessionState: SessionViewState,
  user: AuthenticatedUser,
): JsxNode {
  return (
    <div className="mt-12 space-y-6">
      {renderSessionPanel(
        sessionState,
        runnerState,
        openAiState,
        openRouterState,
      )}
      {renderRunnerPanel(runnerState)}
      <aside
        aria-label="Google account"
        className="flex flex-col gap-5 rounded-3xl border border-white/10 bg-slate-900/80 p-6 sm:flex-row sm:items-center sm:justify-between sm:p-8"
      >
        <div className="flex min-w-0 items-center gap-4">
          {renderAvatar(user)}
          <div className="min-w-0">
            <p className="truncate font-semibold text-white">{user.name}</p>
            <p className="truncate text-sm text-slate-400">{user.email}</p>
          </div>
        </div>
        <button
          className="rounded-2xl border border-white/10 px-5 py-2.5 text-sm font-semibold text-slate-300 transition hover:border-rose-300/30 hover:text-rose-200 disabled:cursor-wait disabled:opacity-60 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-300"
          data-action="logout"
          disabled={logoutPending}
          type="button"
        >
          {logoutPending ? "Signing out…" : "Sign out"}
        </button>
      </aside>
      {renderProviderPanel(OPENAI_PANEL, openAiState)}
      {renderProviderPanel(OPENROUTER_PANEL, openRouterState)}
    </div>
  );
}

function renderApp(
  loadFailed: boolean,
  logoutPending: boolean,
  notices: readonly string[],
  openAiState: ProviderViewState,
  openRouterState: ProviderViewState,
  runnerState: RunnerViewState,
  sessionState: SessionViewState,
  session: AuthSession | undefined,
): JsxNode {
  return (
    <section
      aria-labelledby="app-title"
      className="relative min-h-screen overflow-hidden bg-slate-950 px-6 py-8 text-slate-100 sm:px-10 lg:px-12"
    >
      <div
        aria-hidden="true"
        className="absolute -right-40 -top-40 size-96 rounded-full bg-cyan-500/15 blur-3xl"
      ></div>
      <div
        aria-hidden="true"
        className="absolute -bottom-48 left-1/4 size-96 rounded-full bg-emerald-500/15 blur-3xl"
      ></div>

      <div className="relative mx-auto max-w-6xl">
        {renderHeader(session?.user)}
        <main className="py-12 sm:py-16">
          <p className="text-sm font-semibold tracking-[0.2em] text-emerald-300 uppercase">
            Local control center
          </p>
          <h1
            className="mt-4 text-4xl font-semibold tracking-tight text-white sm:text-6xl"
            id="app-title"
          >
            Q Mush App
          </h1>
          <p className="mt-5 max-w-2xl text-lg leading-8 text-slate-400">
            Coordinate your local swarm from one authenticated workspace.
          </p>

          {notices.map((notice) => (
            <p
              className="mt-8 rounded-2xl border border-amber-300/20 bg-amber-300/10 p-4 text-sm text-amber-100"
              role="alert"
            >
              {notice}
            </p>
          ))}
          {loadFailed
            ? renderSessionError()
            : session === undefined
              ? renderLoadingCard()
              : session.user === null
                ? renderSignIn(session.googleLoginAvailable)
                : renderWorkspace(
                    logoutPending,
                    openAiState,
                    openRouterState,
                    runnerState,
                    sessionState,
                    session.user,
                  )}

          <a
            className="mt-10 inline-flex items-center gap-2 text-sm font-medium text-slate-400 transition hover:text-emerald-200 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-300"
            href={HOME_PATH}
          >
            <span aria-hidden="true">←</span>
            Back to the homepage
          </a>
        </main>
      </div>
    </section>
  );
}

function findAppRoot(): Element {
  const root = document.querySelector("#app");

  if (root === null) {
    throw new Error("The app root was not found");
  }

  return root;
}

const root = findAppRoot();
let loadFailed = false;
let logoutPending = false;
let session: AuthSession | undefined;
const notices = readNotices();
const openAi = new ProviderController(OPENAI_PANEL, () => {
  updateApp(root);
});
const openRouter = new ProviderController(OPENROUTER_PANEL, () => {
  updateApp(root);
});
const runners = new RunnerController(() => {
  updateApp(root);
});
const agentSessions = new SessionController(() => {
  updateApp(root);
});
const providerControllers = [openAi, openRouter] as const;

function resetWorkspaceConnections(): void {
  agentSessions.reset();
  runners.reset();
  for (const controller of providerControllers) {
    controller.reset();
  }
}

async function loadSession(): Promise<void> {
  loadFailed = false;
  session = undefined;
  resetWorkspaceConnections();
  updateApp(root);

  try {
    session = readAuthSession(await requestJson(AUTH_SESSION_PATH));

    if (session.user !== null) {
      await Promise.all([
        agentSessions.load(),
        runners.load(),
        ...providerControllers.map((controller) => controller.load()),
      ]);
    }
  } catch {
    loadFailed = true;
  }

  updateApp(root);
}

async function logout(): Promise<void> {
  logoutPending = true;
  updateApp(root);

  try {
    const response = await fetch(AUTH_LOGOUT_PATH, { method: "POST" });

    if (!response.ok) {
      throw new Error("The logout request failed");
    }

    resetWorkspaceConnections();
    session = {
      googleLoginAvailable: session?.googleLoginAvailable ?? true,
      user: null,
    };
  } catch {
    loadFailed = true;
    session = undefined;
  }

  logoutPending = false;
  updateApp(root);
}

function updateApp(container: Element): void {
  mount(
    renderApp(
      loadFailed,
      logoutPending,
      notices,
      openAi.state,
      openRouter.state,
      runners.state,
      agentSessions.state,
      session,
    ),
    container,
  );
  agentSessions.bind(container);
  runners.bind(container);
  for (const controller of providerControllers) {
    controller.bind(container);
  }

  container
    .querySelector('[data-action="retry-session"]')
    ?.addEventListener("click", () => {
      void loadSession();
    });
  container
    .querySelector('[data-action="logout"]')
    ?.addEventListener("click", () => {
      void logout();
    });
}

function refreshWhileAuthenticated(action: () => Promise<void>): () => void {
  return () => {
    if (session?.user !== null && session?.user !== undefined) {
      void action();
    }
  };
}

window.setInterval(
  refreshWhileAuthenticated(() => agentSessions.refresh()),
  2_000,
);
window.setInterval(
  refreshWhileAuthenticated(() => runners.refresh()),
  15_000,
);

updateApp(root);
void loadSession();

// solid/client.tsx
import {
  createSignal,
  For,
  onCleanup,
  onMount,
  Show,
  type JSX,
} from "solid-js";
import { render } from "solid-js/web";
import {
  isRecord,
  type AuthenticatedUser,
  type AuthSession,
} from "../shared/auth-model.ts";
import {
  AUTH_GOOGLE_PATH,
  AUTH_LOGOUT_PATH,
  AUTH_SESSION_PATH,
  HOME_PATH,
} from "../shared/routes.ts";
import { request, requestJson } from "./browser-http.ts";
import { providerNotice } from "./client-notices.ts";
import {
  BRAVE_SEARCH_PANEL,
  OPENAI_PANEL,
  OPENROUTER_PANEL,
  ProviderPanel,
} from "./provider-client.tsx";
import { ProviderController } from "./provider-controller.ts";
import { PwaController } from "./pwa-controller.tsx";
import { RealtimeConnection } from "./realtime-client.ts";
import {
  renderDebugBoundary,
  RenderDebugLegend,
  RenderDebugProvider,
  RenderDebugToggle,
  RenderDebugView,
} from "./render-debug.tsx";
import { RunnerPanel } from "./runner-client.tsx";
import { RunnerController } from "./runner-controller.ts";
import { SessionPanel } from "./session-client.tsx";
import { SessionController } from "./session-controller.ts";
import "./styles.css";

function readAuthenticatedUser(value: unknown): AuthenticatedUser | null {
  if (value === null) {
    return null;
  }

  if (!isRecord(value)) {
    throw new Error("The session contained an invalid user");
  }

  const email = value["email"];
  const id = value["id"];
  const name = value["name"];
  const picture = value["picture"];

  if (
    typeof email !== "string" ||
    typeof id !== "string" ||
    typeof name !== "string" ||
    (picture !== undefined && typeof picture !== "string")
  ) {
    throw new Error("The session contained an invalid Google profile");
  }

  return picture === undefined
    ? { email, id, name }
    : { email, id, name, picture };
}

function readAuthSession(value: unknown): AuthSession {
  if (!isRecord(value)) {
    throw new Error("The server returned an invalid session");
  }

  const googleLoginAvailable = value["googleLoginAvailable"];

  if (typeof googleLoginAvailable !== "boolean") {
    throw new Error("The server returned an invalid login status");
  }

  return {
    googleLoginAvailable,
    user: readAuthenticatedUser(value["user"]),
  };
}

function readNotices(): readonly string[] {
  const url = new URL(window.location.href);
  const authResult = url.searchParams.get("auth");
  const openAiResult = url.searchParams.get("openai");
  const openRouterResult = url.searchParams.get("openrouter");
  const notices = [
    providerNotice("google", authResult),
    providerNotice("openai", openAiResult),
    providerNotice("openrouter", openRouterResult),
  ].filter((notice) => notice !== undefined);

  if (
    authResult !== null ||
    openAiResult !== null ||
    openRouterResult !== null
  ) {
    url.searchParams.delete("auth");
    url.searchParams.delete("openai");
    url.searchParams.delete("openrouter");
    window.history.replaceState(
      null,
      "",
      `${url.pathname}${url.search}${url.hash}`,
    );
  }

  return notices;
}

function Avatar(props: { readonly user: AuthenticatedUser }): JSX.Element {
  return (
    <Show
      fallback={
        <img
          alt=""
          class="size-12 rounded-2xl bg-slate-800 object-cover ring-1 ring-white/10"
          referrerPolicy="no-referrer"
          src={props.user.picture}
        />
      }
      when={props.user.picture === undefined}
    >
      <span
        aria-hidden="true"
        class="grid size-12 place-items-center rounded-2xl bg-gradient-to-br from-emerald-300 to-cyan-400 text-lg font-bold text-slate-950"
      >
        {props.user.name.charAt(0).toUpperCase()}
      </span>
    </Show>
  );
}

function Header(props: {
  readonly debug: RenderDebugView;
  readonly user: AuthenticatedUser | null | undefined;
}): JSX.Element {
  return (
    <header
      class="flex flex-col gap-4 border-b border-white/10 pb-6 sm:flex-row sm:items-center sm:justify-between"
      {...renderDebugBoundary("header", "Header")}
    >
      <a
        class="inline-flex items-center gap-3 self-start rounded-full font-semibold text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-300"
        href={HOME_PATH}
      >
        <span
          aria-hidden="true"
          class="grid size-10 place-items-center rounded-xl bg-gradient-to-br from-emerald-300 to-cyan-400 text-xl shadow-lg shadow-emerald-950/50"
        >
          🍄
        </span>
        Q Mush
      </a>
      <div class="flex flex-wrap items-center gap-2">
        <RenderDebugToggle view={props.debug} />
        <span class="inline-flex min-w-0 items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/10 px-3 py-1 text-sm text-emerald-200">
          <span
            aria-hidden="true"
            class="size-2 shrink-0 rounded-full bg-emerald-300"
          />
          {props.user === undefined
            ? "Checking session"
            : props.user === null
              ? "Local runtime"
              : `Signed in as ${props.user.name}`}
        </span>
      </div>
    </header>
  );
}

function LoadingCard(): JSX.Element {
  return (
    <div
      class="mt-12 rounded-3xl border border-white/10 bg-white/[0.06] p-8 shadow-2xl shadow-emerald-950/30 backdrop-blur-xl"
      role="status"
    >
      <div class="flex items-center gap-4">
        <span
          aria-hidden="true"
          class="size-3 animate-pulse rounded-full bg-emerald-300 shadow-[0_0_18px_rgba(110,231,183,0.8)]"
        />
        <p class="font-medium text-slate-200">Checking your session…</p>
      </div>
    </div>
  );
}

function SessionError(props: { readonly onRetry: () => void }): JSX.Element {
  return (
    <div
      class="mt-12 rounded-3xl border border-rose-300/20 bg-rose-300/10 p-8"
      role="alert"
    >
      <p class="text-sm font-medium text-rose-200">Connection problem</p>
      <h2 class="mt-3 text-2xl font-semibold text-white">
        We could not check your session
      </h2>
      <p class="mt-3 max-w-xl leading-7 text-slate-300">
        Make sure the local server is running, then try again.
      </p>
      <button
        class="mt-7 rounded-full border border-white/15 px-5 py-2.5 font-semibold text-white transition hover:border-emerald-300/40 hover:text-emerald-200 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-300"
        onClick={props.onRetry}
        type="button"
      >
        Retry
      </button>
    </div>
  );
}

function SignIn(props: {
  readonly googleLoginAvailable: boolean;
  readonly offline: boolean;
}): JSX.Element {
  return (
    <div class="mt-12 grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem]">
      <section
        aria-labelledby="sign-in-title"
        class="rounded-3xl border border-white/10 bg-white/[0.06] p-7 shadow-2xl shadow-emerald-950/30 backdrop-blur-xl sm:p-10"
      >
        <p class="text-sm font-medium text-emerald-300">Secure access</p>
        <h2
          class="mt-3 text-3xl font-semibold tracking-tight text-white"
          id="sign-in-title"
        >
          Sign in to your control center
        </h2>
        <p class="mt-4 max-w-xl leading-7 text-slate-400">
          Use your Google Account to identify yourself. Your Q Mush session
          remains on this machine.
        </p>
        <Show
          fallback={
            <div class="mt-8 rounded-2xl border border-amber-300/20 bg-amber-300/10 p-5 text-amber-100">
              <p class="font-medium">Google login needs configuration</p>
              <p class="mt-2 text-sm leading-6 text-amber-100/70">
                Set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET on the local
                server, then restart it.
              </p>
            </div>
          }
          when={props.googleLoginAvailable}
        >
          <a
            aria-disabled={props.offline}
            class="mt-8 inline-flex w-full items-center justify-center gap-3 rounded-2xl bg-white px-5 py-3 font-semibold text-slate-900 shadow-lg shadow-black/20 transition hover:bg-slate-100 aria-disabled:cursor-not-allowed aria-disabled:opacity-50 active:translate-y-px focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-cyan-300 sm:w-auto"
            href={props.offline ? undefined : AUTH_GOOGLE_PATH}
            onClick={(event) => {
              if (props.offline) {
                event.preventDefault();
              }
            }}
          >
            <span
              aria-hidden="true"
              class="grid size-6 place-items-center rounded-full text-base font-bold text-[#4285f4] ring-1 ring-slate-200"
            >
              G
            </span>
            Continue with Google
          </a>
          <Show when={props.offline}>
            <p class="mt-4 text-sm text-amber-200">
              Reconnect before signing in.
            </p>
          </Show>
        </Show>
      </section>
      <aside
        aria-label="Login details"
        class="rounded-3xl border border-white/10 bg-slate-900/80 p-7 sm:p-8"
      >
        <span
          aria-hidden="true"
          class="grid size-12 place-items-center rounded-2xl border border-cyan-300/20 bg-cyan-300/10 text-xl"
        >
          🔐
        </span>
        <h2 class="mt-6 text-lg font-semibold text-white">
          A small identity boundary
        </h2>
        <ul class="mt-5 space-y-4 text-sm leading-6 text-slate-400">
          <li>Google verifies your account.</li>
          <li>Only your basic profile and email are requested.</li>
          <li>No Google access token is kept after sign-in.</li>
        </ul>
      </aside>
    </div>
  );
}

function Workspace(props: {
  readonly agentSessions: SessionController;
  readonly braveSearch: ProviderController;
  readonly logout: () => Promise<void>;
  readonly logoutPending: boolean;
  readonly openAi: ProviderController;
  readonly openRouter: ProviderController;
  readonly runners: RunnerController;
  readonly user: AuthenticatedUser;
}): JSX.Element {
  return (
    <div
      class="mt-12 space-y-6"
      {...renderDebugBoundary("workspace", "Authenticated workspace")}
    >
      <SessionPanel
        controller={props.agentSessions}
        openAi={props.openAi.view}
        openRouter={props.openRouter.view}
        runners={props.runners.view}
      />
      <RunnerPanel controller={props.runners} />
      <aside
        aria-label="Google account"
        class="flex flex-col gap-5 rounded-3xl border border-white/10 bg-slate-900/80 p-6 sm:flex-row sm:items-center sm:justify-between sm:p-8"
        {...renderDebugBoundary("google-account", "Google account")}
      >
        <div class="flex min-w-0 items-center gap-4">
          <Avatar user={props.user} />
          <div class="min-w-0">
            <p class="truncate font-semibold text-white">{props.user.name}</p>
            <p class="truncate text-sm text-slate-400">{props.user.email}</p>
          </div>
        </div>
        <button
          class="rounded-2xl border border-white/10 px-5 py-2.5 text-sm font-semibold text-slate-300 transition hover:border-rose-300/30 hover:text-rose-200 disabled:cursor-wait disabled:opacity-60 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-300"
          disabled={props.logoutPending}
          onClick={() => {
            void props.logout();
          }}
          type="button"
        >
          {props.logoutPending ? "Signing out…" : "Sign out"}
        </button>
      </aside>
      <ProviderPanel configuration={OPENAI_PANEL} controller={props.openAi} />
      <ProviderPanel
        configuration={OPENROUTER_PANEL}
        controller={props.openRouter}
      />
      <ProviderPanel
        configuration={BRAVE_SEARCH_PANEL}
        controller={props.braveSearch}
      />
    </div>
  );
}

function App(): JSX.Element {
  const [loadFailed, setLoadFailed] = createSignal(false);
  const [offline, setOffline] = createSignal(false);
  const [logoutPending, setLogoutPending] = createSignal(false);
  const [session, setSession] = createSignal<AuthSession>();
  const notices = readNotices();
  const debug = new RenderDebugView();
  const braveSearch = new ProviderController(BRAVE_SEARCH_PANEL);
  const openAi = new ProviderController(OPENAI_PANEL);
  const openRouter = new ProviderController(OPENROUTER_PANEL);
  const runners = new RunnerController();
  const agentSessions = new SessionController();
  const providerControllers = [openAi, openRouter, braveSearch] as const;
  const realtime = new RealtimeConnection((event) => {
    switch (event.type) {
      case "runners":
        runners.applyRealtime(event.runners);
        break;
      case "sessions":
        agentSessions.applyRealtime(event.sessions);
        break;
      case "session":
        agentSessions.applyDetail(event.session);
        break;
      case "session_delta":
        agentSessions.applyDelta(event);
        break;
    }
  });

  const resetWorkspaceConnections = (): void => {
    realtime.stop();
    agentSessions.reset();
    runners.reset();
    for (const controller of providerControllers) {
      controller.reset();
    }
  };

  const loadSession = async (): Promise<void> => {
    setLoadFailed(false);
    setSession(undefined);
    resetWorkspaceConnections();

    try {
      const loaded = readAuthSession(await requestJson(AUTH_SESSION_PATH));
      setSession(loaded);
      if (loaded.user !== null) {
        await Promise.all([
          agentSessions.load(),
          runners.load(),
          ...providerControllers.map((controller) => controller.load()),
        ]);
        realtime.start();
      }
    } catch {
      setLoadFailed(true);
    }
  };

  const logout = async (): Promise<void> => {
    setLogoutPending(true);
    try {
      const response = await request(AUTH_LOGOUT_PATH, { method: "POST" });
      if (!response.ok) {
        throw new Error("The logout request failed");
      }
      resetWorkspaceConnections();
      setSession({
        googleLoginAvailable: session()?.googleLoginAvailable ?? true,
        user: null,
      });
    } catch {
      setLoadFailed(true);
      setSession(undefined);
    } finally {
      setLogoutPending(false);
    }
  };

  onMount(() => {
    void loadSession();
  });
  onCleanup(resetWorkspaceConnections);

  return (
    <RenderDebugProvider view={debug}>
      <section
        aria-labelledby="app-title"
        class="relative min-h-screen overflow-hidden bg-slate-950 px-6 py-8 text-slate-100 sm:px-10 lg:px-12"
        {...renderDebugBoundary("app", "App")}
      >
        <div
          aria-hidden="true"
          class="absolute -right-40 -top-40 size-96 rounded-full bg-cyan-500/15 blur-3xl"
        />
        <div
          aria-hidden="true"
          class="absolute -bottom-48 left-1/4 size-96 rounded-full bg-emerald-500/15 blur-3xl"
        />
        <div class="relative mx-auto max-w-6xl">
          <Header debug={debug} user={session()?.user} />
          <PwaController
            onOfflineChange={setOffline}
            onOnline={() => void loadSession()}
          />
          <main class="py-12 sm:py-16">
            <p class="text-sm font-semibold tracking-[0.2em] text-emerald-300 uppercase">
              Local control center
            </p>
            <h1
              class="mt-4 text-4xl font-semibold tracking-tight text-white sm:text-6xl"
              id="app-title"
            >
              Q Mush App
            </h1>
            <p class="mt-5 max-w-2xl text-lg leading-8 text-slate-400">
              Coordinate your local swarm from one authenticated workspace.
            </p>
            <For each={notices}>
              {(notice) => (
                <p
                  class="mt-8 rounded-2xl border border-amber-300/20 bg-amber-300/10 p-4 text-sm text-amber-100"
                  role="alert"
                >
                  {notice}
                </p>
              )}
            </For>
            <Show
              fallback={<LoadingCard />}
              when={loadFailed() || session() !== undefined}
            >
              <Show
                fallback={<SessionError onRetry={() => void loadSession()} />}
                when={!loadFailed()}
              >
                <Show when={session()}>
                  {(authenticated) => (
                    <Show
                      fallback={
                        <SignIn
                          googleLoginAvailable={
                            authenticated().googleLoginAvailable
                          }
                          offline={offline()}
                        />
                      }
                      when={authenticated().user}
                    >
                      {(user) => (
                        <Workspace
                          agentSessions={agentSessions}
                          braveSearch={braveSearch}
                          logout={logout}
                          logoutPending={logoutPending()}
                          openAi={openAi}
                          openRouter={openRouter}
                          runners={runners}
                          user={user()}
                        />
                      )}
                    </Show>
                  )}
                </Show>
              </Show>
            </Show>
            <a
              class="mt-10 inline-flex items-center gap-2 text-sm font-medium text-slate-400 transition hover:text-emerald-200 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-300"
              href={HOME_PATH}
            >
              <span aria-hidden="true">←</span>
              Back to the homepage
            </a>
          </main>
        </div>
        <RenderDebugLegend view={debug} />
      </section>
    </RenderDebugProvider>
  );
}

const root = document.getElementById("app");
if (root === null) {
  throw new Error("The app root was not found");
}

render(() => <App />, root);
